import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Alert, Button, Checkbox, FormControlLabel, TextField } from "@mui/material";
import { Check, CheckCircle2, ClipboardCheck, CreditCard, FileCheck2, PackageCheck, Search, Truck } from "lucide-react";
import type { RfqRecord } from "../api";

type Quote = { id: string; reference: string; customer: string; email: string; product: string; quantity: number; due: string; value: number | null; status: string; depositPercent?: number; validityDays?: number };
type Order = { id: string; customer: string; item: string; total: number; due: string; status: string; paymentStatus?: string; fulfillment?: string; checklist?: { label: string; done: boolean }[]; revisions?: { label: string; date: string; status: string }[] };
type AdminData = { quotes: Quote[]; orders: Order[] };
const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" });
const demo: AdminData = { quotes: [{ id: "q1", reference: "JP-RFQ-DEMO-1042", customer: "Maya Santos", email: "maya@example.com", product: "Beveled Flame Recognition Award", quantity: 24, due: "Demo date", value: 28800, status: "Quoted", depositPercent: 50, validityDays: 14 }], orders: [{ id: "JP-24018", customer: "Northview Academy", item: "Graduation plaques · 48", total: 67200, due: "Demo date", status: "In production", paymentStatus: "Deposit paid", fulfillment: "Pickup" }] };

function readData(): AdminData {
  let admin = demo;
  try { const saved = localStorage.getItem("jp_admin_poc_v1"); if (saved) admin = { ...demo, ...JSON.parse(saved) }; } catch { /* use demo */ }
  try {
    const rfq = JSON.parse(localStorage.getItem("jp_rfq_state_v1") || "{}") as { records?: RfqRecord[] };
    const ids = new Set(admin.quotes.map((q) => q.id));
    const records: Quote[] = (rfq.records || []).filter((r) => !ids.has(r.id)).map((r) => ({ id: r.id, reference: r.reference, customer: r.draft.contact.name, email: r.draft.contact.email, product: r.productSnapshot?.name || r.draft.details.description || "Custom request", quantity: r.draft.quantity, due: r.draft.deadline.date || "Flexible", value: r.estimate?.total ?? null, status: "New" }));
    admin = { ...admin, quotes: [...records, ...admin.quotes] };
  } catch { /* no local RFQs */ }
  try {
    const quick = JSON.parse(localStorage.getItem("jp_quick_quotes_v1") || "[]") as Array<{ id: string; reference: string; name: string; email: string; mobile: string; productName: string; quantity: number; needBy: string; estimatedTotal: number | null }>;
    const ids = new Set(admin.quotes.map((q) => q.id));
    if (Array.isArray(quick)) admin = { ...admin, quotes: [...quick.filter((q) => !ids.has(q.id)).map((q) => ({ id: q.id, reference: q.reference, customer: q.name, email: q.email, product: q.productName, quantity: q.quantity, due: q.needBy || "Flexible", value: q.estimatedTotal, status: "New" })), ...admin.quotes] };
  } catch { /* no quick requests */ }
  return admin;
}
function saveAction(key: string, value: string) { try { const all = JSON.parse(localStorage.getItem("jp_customer_actions_v1") || "{}"); localStorage.setItem("jp_customer_actions_v1", JSON.stringify({ ...all, [key]: { value, at: new Date().toISOString() } })); } catch { /* storage unavailable */ } }
function readAction(key: string) { try { return JSON.parse(localStorage.getItem("jp_customer_actions_v1") || "{}")[key]?.value || ""; } catch { return ""; } }

export function TrackOrder() {
  const [reference, setReference] = useState(""); const [email, setEmail] = useState(""); const [searched, setSearched] = useState(false);
  const data = useMemo(readData, []);
  const normalized = reference.trim().toLowerCase();
  const quote = data.quotes.find((q) => q.reference.toLowerCase() === normalized && (!q.email || q.email.toLowerCase() === email.trim().toLowerCase()));
  const order = data.orders.find((o) => o.id.toLowerCase() === normalized);
  const result = quote || order;
  return <div className="portal-page"><section className="portal-hero"><div className="container"><span className="eyebrow">QUOTE & ORDER STATUS</span><h1>Follow your request from idea to delivery.</h1><p>Use your reference and email to preview status in this browser.</p><form onSubmit={(e) => { e.preventDefault(); setSearched(true); }} className="portal-search"><TextField required label="Quote or order reference" value={reference} onChange={(e) => { setReference(e.target.value); setSearched(false); }} placeholder="JP-RFQ-… or JP-…"/><TextField label="Email used for the request" type="email" value={email} onChange={(e) => { setEmail(e.target.value); setSearched(false); }}/><Button type="submit" variant="contained" startIcon={<Search size={17}/>}>Check status</Button></form><small>Try the demo quotation: JP-RFQ-DEMO-1042 with maya@example.com, or order: JP-24018.</small></div></section><div className="container portal-result">{searched && !result && <Alert severity="warning">No matching local record was found. Check the reference and email, or remember that POC data stays in the browser where it was created.</Alert>}{searched && quote && <QuoteResult quote={quote}/>} {searched && order && <OrderResult order={order}/>}</div></div>;
}
function QuoteResult({ quote }: { quote: Quote }) { return <section className="portal-card"><div className="portal-card-head"><ClipboardCheck/><div><span>Quotation request</span><h2>{quote.reference}</h2></div><b>{quote.status}</b></div><div className="portal-summary"><div><span>Product</span><strong>{quote.product}</strong></div><div><span>Quantity</span><strong>{quote.quantity}</strong></div><div><span>Requested date</span><strong>{quote.due}</strong></div><div><span>Quoted total</span><strong>{quote.value ? money.format(quote.value) : "Under review"}</strong></div></div><Timeline current={quote.status} items={["New", "Reviewing", "Quoted", "Won"]}/><div className="button-row"><Button component={Link} to={`/quotation/${quote.id}`} variant="contained">View quotation</Button><Button component={Link} to={`/payment-instructions/${quote.id}`}>Payment information</Button></div></section>; }
function OrderResult({ order }: { order: Order }) { return <section className="portal-card"><div className="portal-card-head"><PackageCheck/><div><span>Production order</span><h2>{order.id}</h2></div><b>{order.status}</b></div><div className="portal-summary"><div><span>Order</span><strong>{order.item}</strong></div><div><span>Due</span><strong>{order.due}</strong></div><div><span>Payment</span><strong>{order.paymentStatus || "Unpaid"}</strong></div><div><span>Release</span><strong>{order.fulfillment || "Pickup"}</strong></div></div><Timeline current={order.status} items={["Awaiting artwork", "Design approval", "In production", "Ready", "Completed"]}/><div className="button-row"><Button component={Link} to={`/design-approval/${encodeURIComponent(order.id)}`} variant="contained">Review design</Button><Button component={Link} to={`/payment-instructions/${encodeURIComponent(order.id)}`}>Payment information</Button></div></section>; }
function Timeline({ current, items }: { current: string; items: string[] }) { const index = items.indexOf(current); return <ol className="portal-timeline">{items.map((item, i) => <li key={item} className={i <= index ? "complete" : ""}><span>{i <= index ? <Check size={15}/> : i + 1}</span><strong>{item}</strong></li>)}</ol>; }

export function QuotationPreview() {
  const { id = "" } = useParams(); const data = useMemo(readData, []); const quote = data.quotes.find((q) => q.id === id || q.reference === id); const [accepted, setAccepted] = useState(readAction(`quote:${id}`) === "accepted");
  if (!quote) return <PortalMissing type="quotation"/>;
  const deposit = quote.value ? quote.value * (quote.depositPercent ?? 50) / 100 : null;
  return <div className="container portal-document"><span className="eyebrow">CUSTOMER QUOTATION PREVIEW</span><h1>{quote.product}</h1><p>Prepared for {quote.customer}</p><Alert severity="info">Static POC only. Acceptance is recorded in this browser and is not sent to Just and Pairs.</Alert><dl><div><dt>Reference</dt><dd>{quote.reference}</dd></div><div><dt>Quantity</dt><dd>{quote.quantity}</dd></div><div><dt>Requested date</dt><dd>{quote.due}</dd></div><div><dt>Quotation total</dt><dd>{quote.value ? money.format(quote.value) : "To be confirmed"}</dd></div><div><dt>Required deposit</dt><dd>{deposit ? money.format(deposit) : "To be confirmed"}</dd></div><div><dt>Validity</dt><dd>{quote.validityDays ?? 14} days from formal issue</dd></div></dl><FormControlLabel control={<Checkbox checked={accepted} onChange={(e) => { setAccepted(e.target.checked); saveAction(`quote:${id}`, e.target.checked ? "accepted" : ""); }}/>} label="I accept this quotation preview and understand no real order or payment is created."/>{accepted && <Alert severity="success" icon={<CheckCircle2/>}>Price accepted locally. You can now provide the detailed production information.</Alert>}<div className="button-row"><Button component={Link} to="/track-order">Back to tracking</Button>{accepted && <Button component={Link} to="/project-details" variant="contained">Continue with project details</Button>}<Button component={Link} to={`/payment-instructions/${id}`}>View payment instructions</Button></div></div>;
}
export function DesignApproval() {
  const { id = "" } = useParams(); const data = useMemo(readData, []); const order = data.orders.find((o) => o.id === id); const [decision, setDecision] = useState(readAction(`design:${id}`)); const [notes, setNotes] = useState("");
  if (!order) return <PortalMissing type="design proof"/>;
  return <div className="container portal-document"><span className="eyebrow">DESIGN APPROVAL PREVIEW</span><h1>Review your design proof.</h1><p>{order.item} · {order.id}</p><Alert severity="info">The artwork panel is a placeholder until secure file previews are connected.</Alert><div className="design-proof"><FileCheck2 size={54}/><strong>Customer artwork proof</strong><span>PDF / image preview will appear here</span></div><TextField label="Revision notes" multiline minRows={4} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Describe any requested change"/><div className="button-row"><Button variant="outlined" onClick={() => { setDecision("revision"); saveAction(`design:${id}`, "revision"); }}>Request revision</Button><Button variant="contained" onClick={() => { setDecision("approved"); saveAction(`design:${id}`, "approved"); }}>Approve design preview</Button></div>{decision && <Alert severity={decision === "approved" ? "success" : "warning"}>{decision === "approved" ? "Approval saved locally." : `Revision request saved locally${notes ? `: ${notes}` : "."}`} Nothing has been transmitted.</Alert>}</div>;
}
export function PaymentInstructions() { const { id = "" } = useParams(); return <div className="container portal-document"><CreditCard size={42}/><span className="eyebrow">PAYMENT INFORMATION</span><h1>Payment starts only after confirmation.</h1><Alert severity="warning">This static POC does not collect money and does not display unverified bank or payment-account details.</Alert><div className="payment-steps"><div><span>1</span><div><h2>Receive a formal quotation</h2><p>Confirm the final product, quantity, schedule and price.</p></div></div><div><span>2</span><div><h2>Use verified instructions</h2><p>Payment details will be shown only after the backend and authorized business channels are connected.</p></div></div><div><span>3</span><div><h2>Keep your receipt</h2><p>The future order workspace will record deposit and balance confirmation.</p></div></div></div><p>Reference: <strong>{id}</strong></p><Button component={Link} to="/track-order">Return to tracking</Button></div>; }
function PortalMissing({ type }: { type: string }) { return <div className="container portal-document"><Alert severity="warning">This {type} is not available in this browser.</Alert><Button component={Link} to="/track-order">Check another reference</Button></div>; }
